-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 18:48:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema colegio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colegio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colegio` DEFAULT CHARACTER SET utf8 ;
USE `colegio` ;

-- -----------------------------------------------------
-- Table `colegio`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`alumno` (
  `idalumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `edad` INT NOT NULL,
  `carnet` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idalumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `inicio` VARCHAR(45) NOT NULL,
  `fin` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`asignacion` (
  `idasignacion_curso` INT NOT NULL AUTO_INCREMENT,
  `idalumno` INT NOT NULL,
  `idcurso` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idasignacion_curso`),
  INDEX `fk_asignacion_curso_alumno1_idx` (`idalumno` ASC),
  INDEX `fk_asignacion_curso_curso1_idx` (`idcurso` ASC),
  CONSTRAINT `fk_asignacion_curso_alumno1`
    FOREIGN KEY (`idalumno`)
    REFERENCES `colegio`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacion_curso_curso1`
    FOREIGN KEY (`idcurso`)
    REFERENCES `colegio`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`nota` (
  `idnota` INT NOT NULL AUTO_INCREMENT,
  `idalumno` INT NOT NULL,
  `punteo` DOUBLE NOT NULL,
  `curso` VARCHAR(255) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idnota`),
  INDEX `fk_nota_alumno1_idx` (`idalumno` ASC),
  CONSTRAINT `fk_nota_alumno1`
    FOREIGN KEY (`idalumno`)
    REFERENCES `colegio`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
